### ISSUE TITLE
helpdesk and mail follow after website support on fronted.

### ISSUE THREAD

**Issue by ericzen** [SythilTech/Odoo9#15]
Hi,

This is problem i have, when i use support with receipt of mail.

I've changed in mail models "Suppport Ticket New" and "Suppport Ticket New Ticket (Category)', the From value to associate "helpdesk@domain.tld". I've controled the change is ok.

I create a new support ticket on the website and submit my demand. When i return in mail models, the value is automaticaly replace by "contact@domain.tld".

Why ? Contact is for leads and helpdesk for support.

**Comment by SythilTech** [comment]
Hi,


Sorry this was being taken over by the form controller, I have released 
a new version which should let you change the from address in both those 
emails.


Regards

Steven

**Comment by ericzen** [comment]
Thanks that's work !
