### ISSUE TITLE
Send email in bad language

### ISSUE THREAD

**Issue by ericzen** [SythilTech/Odoo9#18]
When you received an email, a mail is send to the opener and the supervisor.

If you use a different language as english, the send mail is automaticaly send in English. 

Is it possible to change this practice ? 

either a setting language, either the default language of the Mail recipient (partner, or odoo user)

Thanks for your help

**Comment by ericzen** [comment]
Solved

**Comment by SythilTech** [comment]
Hi,


Thank you for reporting this.

I have released a new version, the new ticket category email will now 
use the users language


Regards

Steven
