### ISSUE TITLE
Conflicts with other snippets editing

### ISSUE THREAD

**Issue by avanzella** [SythilTech/Odoo9#3]
Hello,
I am evaluating your component and facing some conflicting behaviours with the website builder in Odoo v9(e).
I appears that after inserting a form, the existing snippets can't be edited anymore (at container level (move, delete or copy commands).
The form itself cannot be moved, deleted or copied either.
As soon as the form is removed from the page (via html editor) , everything goes fine again.
Any idea?
Regards.

**Comment by SythilTech** [comment]
Hello,

Thank you for reporting this.

I am able to replicate this issue on community, I will investigate the 
issue and report back with a fix in the near future.

Regards

Steven

**Comment by SythilBlade** [comment]
Hello,

I have released a new version which fixes this issue.
You will need to update both html_form_builder and html_form_builder_snippets modules

Regards
Steven

**Comment by avanzella** [comment]
Hello,

Everything looks fine now.
Thank you for your quick reaction.

Regards
Alain
