### ISSUE TITLE
Support Page shows internal error 500

### ISSUE THREAD

**Issue by seyed-mohammad-motahar** [SythilTech/Odoo9#4]
After installing the module when user (or admin) goes to website > Support Menu it shows below error.

View 'website_support.support_help_pages' in website 1 not found

Thanks,
Mohammad

**Comment by seyed-mohammad-motahar** [comment]
Please note that above issue is tested in Odoo enterprise (NOT community) 

Thanks,

**Comment by SythilTech** [comment]
Thank you for reporting this, I will get back to you after investigating the issue.
On 28 Sep 2016 6:06 PM, Mohammad <notifications@github.com> wrote:After installing the module when user (or admin) goes to website > Support Menu it shows below error.

View 'website_support.support_help_pages' in website 1 not found

Thanks,
Mohammad

**Comment by SythilTech** [comment]
Hi,
Sorry my first reply as based on your initial message before you mentioned enterprise edition.
Sorry but I do not have access to enterprise edition so I can not test the issue
All I can offer is some general purpose diagnostics.
1. Replace the copy you currently have a newly downloaded copy
2. Restart your Odoo instance
3. Upgrade the module
4 Go to external identifiers and look for 'support_help_pages'
5. Go to user interface->views and search for 'Support Help Pages'

If the view is still is missing then the module is unfortunately not compatible with enterprise.
Sorry I can not be of any further help.

Regards
Steven

**Comment by seyed-mohammad-motahar** [comment]
Hi Steven,

Thanks for your reply and direction and I could get it to work in enterprise now !
