### ISSUE TITLE
html_form_builder_snippets: UnicodeEncodeError when field_description has non-ascii characters

### ISSUE THREAD

**Issue by jbofill** [SythilTech/Odoo9#7]
When using html_form_builder_snippets module, if website language is not English, and some field description has non ascii characters, user can't select any field.

Odoo logs the following error:

`File "odoo/community.addons/html_form_builder_snippets/controllers/main.py", line 44, in form_field_config_general
    field_options_html += "<option value=\"" + str(my_field.id) + "\">" + str(my_field.field_description) + " (" + str(my_field.name) + "/" + str(my_field.ttype) + ")" + "</option>\n"
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf2' in position 13: ordinal not in range(128)`

Workaround in html_form_builder_snippets/controllers/main.py could be to encode field_description:

`field_options_html += "<option value=\"" + str(my_field.id) + "\">" + str(my_field.field_description.encode("utf-8")) + " (" + str(my_field.name) + "/" + str(my_field.ttype) + ")" + "</option>\n"`

**Comment by SythilTech** [comment]
Hi,


I've released a new version which should hopefully fix this.


Regards
Steven

**Comment by jbofill** [comment]
Yes, it does.
Thank you!
